name: Release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for GitHub
        uses: actions/setup-node@v2
        with:
          node-version: [18.x]
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci
      - name: GitHub Release
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.S_STORYBOOK_TOKEN }}
