name: Publish Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js for GitHub
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm install
      - name: GitHub Release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.S_STORYBOOK_TOKEN }}
